# generated by datamodel-codegen:
#   filename:  currentStateVersion.schema.json
#   timestamp: 2026-01-06T20:52:19+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import currentState_schema


class Model(BaseModel):
    version: int
    currentStateId: str
    data: currentState_schema.Model
