# generated by datamodel-codegen:
#   filename:  currentStateVersion.schema.json
#   timestamp: 2026-01-06T21:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import workflow_schema


class Data(BaseModel):
    meetingSummary: str
    workflows: list[workflow_schema.Model]


class Model(BaseModel):
    version: int
    currentStateId: str
    data: Data
