# generated by datamodel-codegen:
#   filename:  currentState.schema.json
#   timestamp: 2026-01-06T21:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    meetingId: str
