# generated by datamodel-codegen:
#   filename:  currentStateVersion.schema.json
#   timestamp: 2026-01-07T20:22:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import workflow_schema


class Data(BaseModel):
    meetingSummary: str
    workflows: list[workflow_schema.Model]
    chunkIndex: int | None = Field(
        None, description='Index of the chunk that produced this version (0-based)'
    )
    chunkText: str | None = Field(
        None, description='The text of the chunk that was processed'
    )


class Model(BaseModel):
    version: int
    currentStateId: str
    data: Data
