# generated by datamodel-codegen:
#   filename:  meeting.schema.json
#   timestamp: 2026-01-08T21:33:25+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Status(Enum):
    active = 'active'
    finalized = 'finalized'


class Model(BaseModel):
    meetingId: str
    status: Status
    orgId: str
    transcript: str | None = Field(
        None, description='The full transcript text uploaded by user'
    )
    totalChunks: int | None = Field(
        None, description='Total number of chunks in the transcript'
    )
