# generated by datamodel-codegen:
#   filename:  processResponse.schema.json
#   timestamp: 2026-01-06T21:46:58+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import currentState_schema


class Model(BaseModel):
    currentState: currentState_schema.Model
