# generated by datamodel-codegen:
#   filename:  processRequest.schema.json
#   timestamp: 2026-01-08T21:33:25+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    meetingId: str
    chunk: str
