# generated by datamodel-codegen:
#   filename:  socketEvent.schema.json
#   timestamp: 2026-01-06T21:33:41+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from . import workflow_schema


class Type(Enum):
    full_state = 'full_state'


class State(BaseModel):
    meetingSummary: str
    workflows: list[workflow_schema.Model]


class Model(BaseModel):
    type: Type
    state: State
