# generated by datamodel-codegen:
#   filename:  socketEvent.schema.json
#   timestamp: 2026-01-06T20:52:19+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from . import currentState_schema


class Type(Enum):
    full_state = 'full_state'


class Model(BaseModel):
    type: Type
    state: currentState_schema.Model
