# generated by datamodel-codegen:
#   filename:  workflow.schema.json
#   timestamp: 2026-01-08T23:03:43+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Type(Enum):
    process = 'process'
    decision = 'decision'
    terminal = 'terminal'


class Variant(Enum):
    start = 'start'
    end = 'end'


class Node(BaseModel):
    id: str
    type: Type
    label: str
    variant: Variant | None = Field(
        None, description="Only used when type is 'terminal'"
    )


class Edge(BaseModel):
    id: str
    source: str
    target: str
    label: str | None = None


class Model(BaseModel):
    id: str
    title: str
    nodes: list[Node]
    edges: list[Edge]
    sources: list[str]
