# generated by datamodel-codegen:
#   filename:  workflow.schema.json
#   timestamp: 2026-01-06T20:52:19+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    id: str
    title: str
    mermaidDiagram: str
    sources: list[str]
